### ISSUE TITLE
Osnovna obdelava in analiza podatkov

### ISSUE THREAD

**Issue by babicvid** [pecarprimoz/PR17_PPGAVB#3]
Do nedelje 30.4

**Comment by pecarprimoz** [comment]
ok boss

**Comment by pecarprimoz** [comment]
Jst delam nad izbirci neko osnovno analizo, kolk je predmetu, keri so najbolj popularni pa zastopani, pol bom še kolk otrok ma posamezna šola.

**Comment by pecarprimoz** [comment]
narejeno [link do commita](https://github.com/pecarprimoz/PR17_PPGAVB/commit/59cc317ad7a6ef3c62568781710063294c22ffd7)

**Comment by pecarprimoz** [comment]
popravljeno od včeraj [link do commita](https://github.com/pecarprimoz/PR17_PPGAVB/commit/1c8560108b317b3dca81e265595756f534af0bda)

**Comment by babicvid** [comment]
Delam analizo nad OŠ in Izob_na_domu

**Comment by pecarprimoz** [comment]
Delam analizo na Oddelkih

**Comment by pecarprimoz** [comment]
Sem oddelal svoje [link do commita](https://github.com/pecarprimoz/PR17_PPGAVB/commit/0d724b36869d779dee90569153139829cd7a48cc)

**Comment by babicvid** [comment]
Narejena analiza, vse dodano na repo, updatan README

**Comment by babicvid** [comment]
Narejeno
