### ISSUE TITLE
Obdelava 2. del

### ISSUE THREAD

**Issue by babicvid** [pecarprimoz/PR17_PPGAVB#5]
Profesor je predlagal, da se osredotočimo na ožjo tematiko.

Predlog je bil, da se pogleda kako se razlikujejo izbrani predmeti glede na regijo, da se podatke oteži (z recimo številom vpisanih otrok), mogoče naredi kakšen model itd.

Lahko se dela tudi kakšna druga stvar, predlogi ↓↓↓

**Comment by pecarprimoz** [comment]
Gregor je naredil povprečje na regijo na specifične tematike, jaz sem naredil regresijski in diskretni model za ocenjevanje regij na podlagi št. otrok oz. če ima specifična šola določen predmet, ali spada v to regijo.

**Comment by pecarprimoz** [comment]
Naredu svoje, razn če je treba še kej dodelat sem zakluču svoj del 
https://github.com/pecarprimoz/PR17_PPGAVB/commit/73412ec6c6198f21cef15bed2bd822ab8e9fce19
